# Generated by Django 5.2.4 on 2025-07-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_greeting_socialmedialinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='achievements/images/')),
                ('image_alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='education/logos/')),
                ('sub_header', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_github_profile', models.BooleanField(default=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplashScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('duration', models.PositiveIntegerField(default=2000)),
                ('animation', models.FileField(upload_to='splash_animations/')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('slides_url', models.URLField()),
                ('event_url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='work_experience/logos/')),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='name',
            new_name='stack_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='ComingSoon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(default='https://comingsoon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greeting',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='greeting',
            name='subtitle',
            field=models.TextField(default='coming soon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='Coming soon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='http://url.project.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='subtitle',
            field=models.TextField(default='coming soon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='coming soon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='techstack',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='techstack',
            name='proficiency',
            field=models.CharField(default='coming soon', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greeting',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='cominf soon', upload_to='projects/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AchievementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='EducationBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=255)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.education')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolio.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_skills', to='portfolio.skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDescBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.workexperience')),
            ],
        ),
    ]
